# ============================================================
# Namespace
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: "2401008"

---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: "2401008"
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


# ============================================================
# PostgreSQL Deployment
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: "2401008"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "healthtracker_2401008"
            - name: POSTGRES_USER
              value: "samarth"
            - name: POSTGRES_PASSWORD
              value: "Samarth@2025"
          ports:
            - containerPort: 5432

---

# ============================================================
# PostgreSQL Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: "2401008"
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

# ============================================================
# Django Deployment
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-tracker-deployment
  namespace: "2401008"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-tracker
  template:
    metadata:
      labels:
        app: health-tracker
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: health-tracker
          image: 127.0.0.1:30085/2401008_sam/health-tracker:latest
          ports:
            - containerPort: 8000

          env:
            - name: DB_NAME
              value: "healthtracker_2401008"

            - name: DB_USER
              value: "samarth"

            - name: DB_PASSWORD
              value: "Samarth@2025"

            - name: DB_HOST
              value: "postgres-service"

            - name: DB_PORT
              value: "5432"

            - name: DEBUG
              value: "0"

---

# ============================================================
# Django Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: health-tracker-service
  namespace: "2401008"
spec:
  selector:
    app: health-tracker
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---

# ============================================================
# Ingress
# ============================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-tracker-ingress
  namespace: "2401008"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: health-tracker.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: health-tracker-service
                port:
                  number: 8000
