"""
Django settings for health_tracker project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see:
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Note: In production, this should be stored as an environment variable
SECRET_KEY = "django-insecure-(y4(vqbx=jfnt%qxtsq3^k6$3!s(=j&+gmdfaws&sy%y=px)hz"

# SECURITY WARNING: don't run with debug turned on in production!
# Debug mode should be False in production for security
DEBUG = True

# Hosts that this Django application can serve
# For production, add your domain names here
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Django built-in apps
    "django.contrib.admin",          # Admin interface
    "django.contrib.auth",           # Authentication system
    "django.contrib.contenttypes",   # Content type system
    "django.contrib.sessions",      # Session management
    "django.contrib.messages",       # Message framework
    "django.contrib.staticfiles",    # Static file management
    
    # Local apps
    "tracker",                      # Health tracker application
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",          # Security enhancements
    "django.contrib.sessions.middleware.SessionMiddleware",   # Session management
    "django.middleware.common.CommonMiddleware",              # URL normalization
    "django.middleware.csrf.CsrfViewMiddleware",              # CSRF protection
    "django.contrib.auth.middleware.AuthenticationMiddleware",# User authentication
    "django.contrib.messages.middleware.MessageMiddleware",   # Message framework
    "django.middleware.clickjacking.XFrameOptionsMiddleware", # Clickjacking protection
]

# Root URL configuration
ROOT_URLCONF = "health_tracker.urls"

# Template configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],  # Look for templates in project-level templates directory
        "APP_DIRS": True,                  # Enable template discovery in each app's "templates" directory
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            'libraries': {
                'staticfiles': 'django.templatetags.static',  # Make staticfiles tag available
            }
        },
    },
]

# WSGI application for deployment
WSGI_APPLICATION = "health_tracker.wsgi.application"

# Database configuration
# Using PostgreSQL as the database backend
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # PostgreSQL database engine
        'NAME': 'healthtracker',                    # Database name
        'USER': 'postgres',                        # Database user
        'PASSWORD': 'postgresql123',               # Database password
        'HOST': 'localhost',                       # Database host
        'PORT': '5432',                            # Database port
    }
}

# Password validation
# These validators help ensure strong passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # Ensures password isn't too similar to user attributes
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        # Ensures password meets minimum length requirement
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        # Prevents common passwords
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        # Ensures password isn't entirely numeric
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"  # Default language

TIME_ZONE = "UTC"        # Default timezone

USE_I18N = True          # Enable internationalization

USE_TZ = True            # Enable timezone support

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"  # URL prefix for static files

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"  # Default field type for primary keys

# Authentication settings
LOGIN_REDIRECT_URL = 'dashboard'    # Where to redirect after successful login
LOGOUT_REDIRECT_URL = 'login'       # Where to redirect after logout
LOGIN_URL = 'login'                 # URL to redirect to for login (used by @login_required)

# Static files configuration
STATICFILES_DIRS = [BASE_DIR / "static"]  # Additional directories for static files during development
STATIC_ROOT = BASE_DIR / "staticfiles"    # Directory where static files will be collected for production