# Generated by Django 4.2.20 on 2025-04-07 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
