# Generated by Django 4.2.20 on 2025-04-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_healthrecord_date"),
    ]

    operations = []
