# Generated by Django 4.2.20 on 2025-04-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0003_auto_20250407_2329"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthrecord",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of the health record"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="sleep_hours",
            field=models.FloatField(default=0, help_text="Hours of sleep"),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="steps",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of steps taken"
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="water_intake_ml",
            field=models.PositiveIntegerField(
                default=0, help_text="Water intake in milliliters"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="healthrecord",
            unique_together={("user", "date")},
        ),
    ]
